### ISSUE TITLE
Tsumino downloads in progress can be broken once the session cookie expires

### ISSUE THREAD

**Issue by wightwulf1944** [csaki/Hentoid#91] opened 2016-02-25 10:53 UTC
Affects version 1.1.6r1

Repro steps:
1. Start a tsumino download. It is recommended to select content with over 300 pages.
2. Wait for download to finish.

Result: The download in progress may get interrupted before it is completed. Hentoid will state it has been completed with errors.

Expected result: If the session cookie expires while a download is in progress, the download should halt and alert the user.

Notes:
* Not device or OS dependent
* Session cookie duration is unknown.
* Once a download has been broken, it cannot be normally resumed even after re-doing the captcha.
* More details will follow after testing

**Comment by avluis** [comment] 2016-03-04 21:51
Seems like we may have a user with this particular issue as well, check out [this](http://fakkudroid.blogspot.com/2016/02/hentoid-116r1.html?showComment=1456560685459#c8985600962111599704) thread.
I'm still deciphering the last comment, but the gist of it seems to be related to this.

**Comment by avluis** [comment] 2016-04-02 20:34
[This answers](http://stackoverflow.com/a/17299055/1615876) some of my suspicions - we basically need to reset cookies manually when a download is in the error state for this source - and then reload the url to have the user grab a new session, then resume the download with the new session cookie.

As for checking if the session cookie is still good for use - we need to find a page we can use to validate results with a bad session vs. results with a good session.

**Comment by avluis** [comment] 2016-04-20 18:01
After changes with how tsumino works, this issue may be outdated - once they implemented downloads from their website and relaxed (or removed entirely) their captcha system, I have not come across this issue.

Unless this can be reproduced, I will go ahead and close this one out.
Please re-open with more details if that is not the case.

**Closed by avluis** 2016-04-20 18:01 UTC
Labels: bug
