### ISSUE TITLE
Download button doesn't show on Fakku and Hitomi

### ISSUE THREAD

**Issue by maphie14** [csaki/Hentoid#45] opened 2015-10-30 08:54 UTC
Affects version 1.1.3

**Notes:**
 * It was working fine for hitomi before update.
 * The changes made to allow the download button to work on Fakku work separately from the parsers for Hitomi and Pururin

**Confirmed with ff devices:**

Device | OS | logs
---- | ---- | ----
Samsung Galaxy Tab 3 (SM-T210R) | 4.1.2 | **[mediafire](https://www.mediafire.com/?y5b1vf8ieokz6am)**
Samsung Galaxy S2 (GT-9100) | 4.1.2 | n/a
Samsung Galaxy Duos (GT-S7562) | 4.0.4 | n/a
Samsung Galaxy Young (GT-S6310) | 4.1.2 | https://drive.google.com/file/d/0B6esBD0mU-v6bVlOR2xjRUdhZTQ/view?usp=sharing

**Screenshots:**

V 1.1.2 | V 1.1.3
---- | ----
![72066058-7f7c-11e5-84d7-3fdd77a3fed4](https://cloud.githubusercontent.com/assets/2737347/10863241/15f64e78-8002-11e5-9596-9869aac64c5d.png) | ![71a6a82a-7f7c-11e5-8003-90e522271a27](https://cloud.githubusercontent.com/assets/2737347/10863244/227e882c-8002-11e5-879a-fc3061fc2a11.png)
![717452e4-7f7c-11e5-8b41-5c38818e0e8e](https://cloud.githubusercontent.com/assets/2737347/10863247/339fe9e8-8002-11e5-915e-1f08bc38c13f.png) | ![71c8f920-7f7c-11e5-8205-6ebfa5230a26](https://cloud.githubusercontent.com/assets/2737347/10863248/38369d80-8002-11e5-9a5f-f92ab64cefb7.png)
![71795cb2-7f7c-11e5-8cbe-e8fd096f1caa](https://cloud.githubusercontent.com/assets/2737347/10863252/41c9b936-8002-11e5-9082-0ba195bbbe97.png) | ![71d57a7e-7f7c-11e5-8482-1fbeb8ab77ed](https://cloud.githubusercontent.com/assets/2737347/10863256/46987f9c-8002-11e5-8722-a40cde204362.png)

**Comment by wightwulf1944** [comment] 2015-10-30 14:55
I'm reviewing this one now. Probably just a dupe.

**Comment by wightwulf1944** [comment] 2015-10-30 18:01
Cannot reproduce bug. Closing ticket.

version 1.1.3
OS Android 4.2.2, 5, 5.1
Wifi, Mobile.

**Comment by avluis** [comment] 2015-10-30 18:32
The changes made to allow the download button to work on Fakku work separately from the parsers for Hitomi and Pururin, so yes - this issue is not related to that fix.

**Comment by maphie14** [comment] 2015-10-30 19:11
I made some screenshots for you

As you can see I am using 1.1.2 at first notice the noti for update
![screenshot_2015-10-31-02-51-10](https://cloud.githubusercontent.com/assets/8255824/10855431/72066058-7f7c-11e5-84d7-3fdd77a3fed4.png)
![screenshot_2015-10-31-02-52-15](https://cloud.githubusercontent.com/assets/8255824/10855425/717452e4-7f7c-11e5-8b41-5c38818e0e8e.png)
![screenshot_2015-10-31-02-55-59](https://cloud.githubusercontent.com/assets/8255824/10855426/71795cb2-7f7c-11e5-8cbe-e8fd096f1caa.png)
![screenshot_2015-10-31-02-56-35](https://cloud.githubusercontent.com/assets/8255824/10855427/719ec542-7f7c-11e5-8bd2-4fb35114c133.png)

then I updated to 1.1.3 then no download button
![screenshot_2015-10-31-02-59-33](https://cloud.githubusercontent.com/assets/8255824/10855428/71a6a82a-7f7c-11e5-8003-90e522271a27.png)
![screenshot_2015-10-31-02-59-56](https://cloud.githubusercontent.com/assets/8255824/10855429/71c8f920-7f7c-11e5-8205-6ebfa5230a26.png)
![screenshot_2015-10-31-03-04-49](https://cloud.githubusercontent.com/assets/8255824/10855430/71d57a7e-7f7c-11e5-8482-1fbeb8ab77ed.png)

btw I am using 4.1.2 android OS
SM-T210R

If you want some log while using it. Is catlog okay for you?

**Comment by avluis** [comment] 2015-10-30 19:19
The fix seems to be working completely opposite to how it is working on my test devices, go ahead and attach a logcat to this via pastebin.

**Comment by maphie14** [comment] 2015-10-30 19:40
It exceeded the 512kb filesize of pastebin so I uploaded it to mediafire

https://www.mediafire.com/?y5b1vf8ieokz6am

**Comment by wightwulf1944** [comment] 2015-10-31 11:02
Can you also try clearing data of Hentoid. Then reimport your library so that you dont lose anything and try again.

**Comment by maphie14** [comment] 2015-10-31 16:24
I tried fresh install and still no Download button

**Comment by avluis** [comment] 2015-10-31 19:26
We may need an additional device that can reproduce this issue - has anyone else from the forum reported this issue after installing 1.1.3?

**Comment by wightwulf1944** [comment] 2015-10-31 22:43
Yeah we got a few. Im starting to see a trend with the os version.

Samsung Galaxy S2 (GT-9100)
Android Version: 4.1.2
Samsung Galaxy Duos (GT-S7562)
Android Version: 4.0.4

Thanks to andrew lam and hideyoshi kinoshita for the info.

**Comment by avluis** [comment] 2015-10-31 23:04
So both Samsung devices running Android < 5.0.

Also, what do you think of Hideyoshi?

**Comment by avluis** [comment] 2015-10-31 23:10
@maphie14 @wightwulf1944 
Please give this build a try:
https://drive.google.com/file/d/0BycOIcYbBvF_ckpubl9EUFlIbDQ/view?usp=sharing

See if there is any difference.

**Comment by maphie14** [comment] 2015-11-01 06:26
tried it still no download button
both fakku and hitomi

**Comment by wightwulf1944** [comment] 2015-11-01 10:04
Tested using 1.1.4-a
Samsung Galaxy Y (GT-S6310)
OS: 4.1.2
No download button on both hitomi and fakku.
Logs incoming...

**Comment by avluis** [comment] 2015-11-01 14:41
@wightwulf1944 
That log you sent me only has info on Hentoid until the point it checks for updates - no activity, details or info after that about the app and browsing to the affected websites.
Can you give it another try?

Also, I am seeing a lot of this:
```
11-01 18:21:22.809 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.809 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.819 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.819 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.819 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.819 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.819 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.819 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.829 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.829 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.829 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.829 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.829 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.829 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.829 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.829 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.829 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.829 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.839 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.839 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.839 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.839 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.839 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.839 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.839 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.839 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.849 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.849 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.849 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.849 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.859 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.859 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.859 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.859 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.859 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.859 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
11-01 18:21:22.859 D/FirewallPolicy(449): getURLFilterEnabled(true)
11-01 18:21:22.859 D/FirewallPolicy(449): isUrlBlocked - Policy disabled
```

**Comment by avluis** [comment] 2015-11-01 14:54
@maphie14 @wightwulf1944 
Here is a [debug build](https://drive.google.com/file/d/0BycOIcYbBvF_NTBQUGlyM2V5NlE/view?usp=sharing) for you guys - based on 1.1.4-alpha.

**Comment by avluis** [comment] 2015-11-01 17:54
@maphie14 Please try [release 1.1.4](https://github.com/csaki/Hentoid/releases/tag/v1.1.4)~
Let me know if you are still having issues.

**Closed** 2015-11-01 19:15 UTC
Labels: bug

**Comment by maphie14** [comment] 2015-11-03 04:05
Tried release 1.1.4

Works fine for Fakku and Hitomi

**Comment by avluis** [comment] 2015-11-03 17:51
@maphie14 Thanks for confirming!
